[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,NEXT_PUBLIC_SUPABASE_URL"

# No-cache headers for API routes and dynamic content
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/lessons/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/traces/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"


 
# Aggressive caching for main page (loads once, never refreshes)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"

[[headers]]
  for = "/*?_rsc=*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"
