import Anthropic from '@anthropic-ai/sdk';
import { 
  SYSTEM_PROMPT, 
  getUserPrompt, 
  extractTitle, 
  extractKeyConcepts, 
  extractPrerequisites, 
  extractDuration,
  type LessonGenerationOptions 
} from './prompts';

// Initialize Anthropic client lazily to avoid errors when API key is not set
function getAnthropicClient() {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY environment variable is not set');
  }
  return new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
  });
}

export interface GeneratedLesson {
  title: string;
  content: string;
  estimatedDuration: number;
  difficulty: string;
  keyConcepts: string[];
  prerequisites: string[];
}

export async function generateLessonWithAnthropic(options: LessonGenerationOptions): Promise<GeneratedLesson> {
  const {
    difficulty = 'intermediate',
    duration = 30
  } = options;

  const systemPrompt = SYSTEM_PROMPT;
  const userPrompt = getUserPrompt(options);

  try {
    const anthropic = getAnthropicClient();
    const message = await anthropic.messages.create({
      model: "claude-3-5-sonnet-20241022",
      max_tokens: 4000,
      temperature: 0.7,
      system: systemPrompt,
      messages: [
        { role: "user", content: userPrompt }
      ]
    });

    const content = message.content[0];
    if (content.type !== 'text') {
      throw new Error('Unexpected response type from Anthropic');
    }

    const lessonContent = content.text;
    if (!lessonContent) {
      throw new Error('No content generated by Anthropic');
    }

    // Extract structured information from the generated content
    const title = extractTitle(lessonContent);
    const keyConcepts = extractKeyConcepts(lessonContent);
    const prerequisites = extractPrerequisites(lessonContent);
    const estimatedDuration = extractDuration(lessonContent) || duration;

    return {
      title,
      content: lessonContent,
      estimatedDuration,
      difficulty,
      keyConcepts,
      prerequisites
    };
  } catch (error) {
    console.error('Anthropic API error:', error);
    throw new Error(`Failed to generate lesson: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}
