import Groq from 'groq-sdk';
import { 
  SYSTEM_PROMPT, 
  getUserPrompt, 
  extractTitle, 
  extractKeyConcepts, 
  extractPrerequisites, 
  extractDuration,
  type LessonGenerationOptions 
} from './prompts';

// Initialize Groq client lazily to avoid errors when API key is not set
function getGroqClient() {
  if (!process.env.GROQ_API_KEY) {
    throw new Error('GROQ_API_KEY environment variable is not set');
  }
  return new Groq({
    apiKey: process.env.GROQ_API_KEY,
  });
}

export interface GeneratedLesson {
  title: string;
  content: string;
  estimatedDuration: number;
  difficulty: string;
  keyConcepts: string[];
  prerequisites: string[];
}

export async function generateLessonWithGroq(options: LessonGenerationOptions): Promise<GeneratedLesson> {
  const {
    difficulty = 'intermediate',
    duration = 30
  } = options;

  const systemPrompt = SYSTEM_PROMPT;
  const userPrompt = getUserPrompt(options);

  try {
    const groq = getGroqClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant", // Updated to current free model on Groq
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      max_tokens: 4000,
      temperature: 0.7,
    });

    const content = completion.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No content generated by Groq');
    }

    // Extract structured information from the generated content
    const title = extractTitle(content);
    const keyConcepts = extractKeyConcepts(content);
    const prerequisites = extractPrerequisites(content);
    const estimatedDuration = extractDuration(content) || duration;

    return {
      title,
      content,
      estimatedDuration,
      difficulty,
      keyConcepts,
      prerequisites
    };
  } catch (error) {
    console.error('Groq API error:', error);
    throw new Error(`Failed to generate lesson with Groq: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}
